### PR TITLE
Update GNOME Platform 46

### PR DESCRIPTION
**Pull request by travier**

### CODE REVIEW

**Comment by travier** [comment]
```
{
    "errors": [
        "appstream-failed-validation"
    ],
    "warnings": [
        "appstream-summary-too-long",
        "appstream-screenshot-missing-caption"
    ],
    "appstream": [
        "E: org.gnome.SoundRecorder.desktop:479: custom-key-duplicated Purism::form_factor"
    ],
    "message": "Please consult the documentation at https://docs.flathub.org/docs/for-app-authors/linter"
}
```

**Comment by travier** [comment]
https://gitlab.gnome.org/World/vocalis/-/merge_requests/223

**Comment by alatiera** [comment]
bot, build

**Comment by alatiera** [comment]
Either backporting the patch or renaming and EOLing and updating to a more recent release

**Comment by AsciiWolf** [comment]
Any update?

**Comment by travier** [comment]
Done in https://github.com/flathub/org.gnome.SoundRecorder/pull/16

**Pull request closed without merging**
