### PR TITLE
Bump runtime to 3.30

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by felipeborges** [comment]
Does this work for you? I get some cairo related bugs while trying SoundRecorder with the 3.30 runtime.

**Comment by bilelmoussaoui** [comment]
Oops, it doesn't even run on my case 
```
(org.gnome.SoundRecorder:2): Gjs-CRITICAL **: 14:05:58.026: JS ERROR: SyntaxError: missing ) after catch @ resource:///org/gnome/SoundRecorder/js/listview.js:114
Script /app/bin/gnome-sound-recorder threw an exception
```
might worth patching those issues upstream.

**Comment by bilelmoussaoui** [comment]
Fixed that issue by using a patch from Fedora guys.
```
From 455ba5f9e327b6d9495b1fd7dc5dd0a6bd95ae99 Mon Sep 17 00:00:00 2001
From: Tim Lunn <tim@feathertop.org>
Date: Mon, 10 Sep 2018 18:02:03 +1000
Subject: [PATCH] Remove usage of conditional catch statements

The are no longer supported in mozjs60

Closes https://gitlab.gnome.org/GNOME/gnome-sound-recorder/issues/35
---
 src/listview.js | 5 ++++-
 1 file changed, 4 insertions(+), 1 deletion(-)

diff --git a/src/listview.js b/src/listview.js
index 33cbec0..afe508a 100644
--- a/src/listview.js
+++ b/src/listview.js
@@ -111,7 +111,10 @@ const Listview = new Lang.Class({
                                     if (returnedNumber > trackNumber)
                                         trackNumber = returnedNumber;
 
-                                }  catch (e if e instanceof TypeError) {
+                                }  catch (e) {
+                                    if (!e instanceof TypeError)
+                                        throw e;
+
                                     log("Tracknumber not returned");
                                     // Don't handle the error
                                 }
-- 
2.18.0
```
It does fixes the issues but I still get a lot of issues :(
```
(org.gnome.SoundRecorder:2): Gjs-WARNING **: 14:56:56.712: Some code accessed the property 'Application' on the module 'application'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Gtk-Message: 14:56:56.821: Failed to load module "pk-gtk-module"
Gtk-Message: 14:56:56.823: Failed to load module "pk-gtk-module"
Gjs-Message: 14:56:56.840: JS LOG: Sound Recorder started
Gjs-Message: 14:56:56.852: JS WARNING: [resource:///org/gnome/SoundRecorder/js/application.js 84]: Too many arguments to function Gst.init: expected 1, got 2

(org.gnome.SoundRecorder:2): Gjs-WARNING **: 14:56:57.332: Some code accessed the property 'MainWindow' on the module 'mainWindow'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

(org.gnome.SoundRecorder:2): Gjs-WARNING **: 14:56:57.333: Some code accessed the property 'AudioProfile' on the module 'audioProfile'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

(org.gnome.SoundRecorder:2): Gjs-WARNING **: 14:56:57.334: Some code accessed the property 'OffsetController' on the module 'fileUtil'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

(org.gnome.SoundRecorder:2): Gjs-WARNING **: 14:56:57.334: Some code accessed the property 'DisplayTime' on the module 'fileUtil'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

(org.gnome.SoundRecorder:2): Gjs-WARNING **: 14:56:57.337: Some code accessed the property 'Listview' on the module 'listview'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

(org.gnome.SoundRecorder:2): Gjs-WARNING **: 14:56:57.338: Some code accessed the property 'Record' on the module 'record'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

(org.gnome.SoundRecorder:2): Gjs-WARNING **: 14:56:57.340: Some code accessed the property 'Play' on the module 'play'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

(org.gnome.SoundRecorder:2): Gjs-WARNING **: 14:56:57.587: Some code accessed the property 'offsetController' on the module 'mainWindow'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

(org.gnome.SoundRecorder:2): Gjs-WARNING **: 14:56:57.587: Some code accessed the property 'list' on the module 'mainWindow'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

(org.gnome.SoundRecorder:2): Gjs-WARNING **: 14:56:57.587: Some code accessed the property 'view' on the module 'mainWindow'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

(org.gnome.SoundRecorder:2): Gjs-WARNING **: 14:56:57.587: Some code accessed the property 'application' on the module 'application'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

(org.gnome.SoundRecorder:2): Gjs-WARNING **: 14:56:59.710: Some code accessed the property 'audioProfile' on the module 'mainWindow'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

(org.gnome.SoundRecorder:2): Gjs-WARNING **: 14:56:59.779: Some code accessed the property 'SIGINT' on the module 'application'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Gjs-Message: 14:56:59.779: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 154]: Too many arguments to function GLib.unix_signal_add: expected 3, got 4

(org.gnome.SoundRecorder:2): Gjs-WARNING **: 14:56:59.779: Some code accessed the property 'SIGTERM' on the module 'application'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Gjs-Message: 14:56:59.779: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 155]: Too many arguments to function GLib.unix_signal_add: expected 3, got 4

(org.gnome.SoundRecorder:2): Gjs-WARNING **: 14:56:59.841: Some code accessed the property '_SEC_TIMEOUT' on the module 'mainWindow'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

(org.gnome.SoundRecorder:2): Gjs-WARNING **: 14:56:59.841: Some code accessed the property 'WaveForm' on the module 'waveform'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Gjs-Message: 14:56:59.853: JS WARNING: [resource:///org/gnome/SoundRecorder/js/waveform.js 174]: reference to undefined property "recordTime"
Gjs-Message: 14:56:59.942: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:00.043: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:00.143: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:00.244: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:00.344: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:00.445: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:00.545: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:00.646: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:00.746: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:00.847: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:00.948: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:01.048: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:01.149: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:01.249: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:01.350: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:01.451: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:01.552: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:01.652: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:01.753: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:01.854: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:01.955: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:02.056: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:02.156: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:02.257: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:02.357: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:02.458: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:02.558: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:02.658: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:02.759: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:02.860: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:02.960: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:03.061: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:03.161: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:03.262: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:03.363: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:03.463: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:03.564: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:03.664: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:03.765: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:03.866: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:03.967: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:04.067: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:04.168: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2
Gjs-Message: 14:57:04.219: JS LOG: error
Gjs-Message: 14:57:04.235: JS WARNING: [resource:///org/gnome/SoundRecorder/js/record.js 159]: Too many arguments to method Gst.Element.query_position: expected 1, got 2

(org.gnome.SoundRecorder:2): Gjs-WARNING **: 14:57:04.332: Some code accessed the property 'recordPipeline' on the module 'mainWindow'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

(org.gnome.SoundRecorder:2): Gjs-WARNING **: 14:57:04.332: Some code accessed the property 'RecordPipelineStates' on the module 'mainWindow'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

(org.gnome.SoundRecorder:2): Gjs-WARNING **: 14:57:04.337: Some code accessed the property 'displayTime' on the module 'mainWindow'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

(org.gnome.SoundRecorder:2): Gjs-WARNING **: 14:57:04.351: Some code accessed the property 'containerProfileMap' on the module 'audioProfile'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

(org.gnome.SoundRecorder:2): Gjs-WARNING **: 14:57:04.351: Some code accessed the property 'audioCodecMap' on the module 'audioProfile'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

** (org.gnome.SoundRecorder:2): CRITICAL **: 14:57:05.703: g_object_info_get_n_fields: assertion 'info != NULL' failed
**
Gjs:ERROR:gi/object.cpp:478:bool ObjectInstance::field_getter_impl(JSContext*, JS::HandleObject, JS::HandleString, JS::MutableHandleValue): assertion failed: (field)
```
This really needs some love from upstream, but it seems no one is maintaing it currently :( will see if I can find some time to push some fixes upstream.

**Comment by nedrichards** [comment]
Runtime is now 3.30

**Pull request closed without merging**
